version: '3.8'  
services:
  calculator:
    build: . 
    image: nancetech/compose-calculator-microservice:latest
    ports:
      - "4000:4000"
    restart:
      unless-stopped
    volumes:
      - ./logs:/usr/src/logs
    environment:
      - NODE_ENV=production
    healthcheck:
      test: curl http://localhost:4000 || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 40s
